name: Deploy to EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: npm test
        
      - name: Build application
        run: npm run build
        
      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
          
      - name: Setup known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
          
      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          # Compactar arquivos necessários para implantação
          tar -czf deploy.tar.gz dist/ package.json package-lock.json ecosystem.config.js
          
          # Enviar arquivos para o servidor
          scp deploy.tar.gz $EC2_USER@$EC2_HOST:/home/$EC2_USER/
          
          # Executar comandos de implantação no servidor
          ssh $EC2_USER@$EC2_HOST << 'ENDSSH'
            # Navegar para o diretório do projeto backend
            cd /home/$EC2_USER/sistema-de-rachas-backend
            
            # Extrair arquivos
            tar -xzf /home/$EC2_USER/deploy.tar.gz
            
            # Instalar dependências de produção
            npm ci --production
            
            # Reiniciar a aplicação com PM2
            pm2 restart ecosystem.config.js
            
            # Limpar arquivos temporários
            rm /home/$EC2_USER/deploy.tar.gz
          ENDSSH 